# Generated by Django 3.0.4 on 2020-03-17 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20200317_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.Site_User')),
                ('sem', models.IntegerField()),
                ('div', models.IntegerField()),
                ('batch', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('teach_id', models.AutoField(primary_key=True, serialize=False)),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_id', to='login.Site_User')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Rules',
            fields=[
                ('pr_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_team', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('max_team', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('is_cross_divsion', models.BooleanField(default=False)),
                ('is_cross_batch', models.BooleanField(default=False)),
                ('sub_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('rule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_id', to='stu_dashboard.Project_Rules')),
            ],
        ),
    ]
