# Generated by Django 3.0.4 on 2020-03-18 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 9, 52, 23, 814645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(max_length=1),
        ),
    ]
