# Generated by Django 3.0.4 on 2020-03-18 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0002_auto_20200318_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_id',
            new_name='site_user',
        ),
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 15, 44, 43, 626386, tzinfo=utc)),
        ),
    ]
