# Generated by Django 3.0.4 on 2020-03-18 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0010_auto_20200319_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Project_Rules'),
        ),
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 18, 54, 13, 257849, tzinfo=utc)),
        ),
    ]
