# Generated by Django 3.0.4 on 2020-03-20 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0013_auto_20200319_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 15, 19, 40, 261454, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('leader_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stu_dashboard.Team'),
        ),
    ]
