# Generated by Django 3.0.4 on 2020-03-20 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0015_auto_20200320_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='team_id',
        ),
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 16, 49, 28, 479768, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Team_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Student')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Team')),
            ],
        ),
    ]
