# Generated by Django 3.0.4 on 2020-03-21 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0016_auto_20200320_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 6, 53, 23, 430747, tzinfo=utc)),
        ),
    ]
