# Generated by Django 3.0.4 on 2020-03-21 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0017_auto_20200321_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 16, 5, 43, 857885, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='team_student',
            unique_together={('team_id', 'student_id')},
        ),
    ]
