# Generated by Django 3.0.4 on 2020-03-23 11:04

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0019_auto_20200321_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 11, 4, 50, 65130, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TeamPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefernce', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Team')),
            ],
            options={
                'unique_together': {('team', 'project')},
            },
        ),
    ]
