# Generated by Django 3.0.4 on 2020-03-23 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0021_auto_20200323_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 11, 13, 49, 354342, tzinfo=utc)),
        ),
    ]
