# Generated by Django 3.0.4 on 2020-04-25 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0026_auto_20200325_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 10, 52, 53, 251714, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='AllocatedProject',
            fields=[
                ('allocated_id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu_dashboard.Team')),
            ],
        ),
    ]
