# Generated by Django 3.0.4 on 2020-04-26 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stu_dashboard', '0028_auto_20200425_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cpi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project_rules',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 7, 59, 56, 874392, tzinfo=utc)),
        ),
    ]
