# Generated by Django 3.0.4 on 2020-03-17 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Login',
            new_name='Site_User',
        ),
    ]
