# Generated by Django 3.0.4 on 2020-03-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_auto_20200318_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_user',
            name='id',
        ),
        migrations.AlterField(
            model_name='site_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_id', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
